nodeshift/opossum

examples/jquery/index.js

i'm not sure if bug is the correct label here

bug: removing unused util import in jquery example

---

package.json

Closes #25
https://greenkeeper.io/

chore(package): update tape-run to version 2.4.1

---

lib/circuit.js
test/test.js

adds the group option and defaults to use the name property if none is provided

feat: add a group option.  GH-Issue #43

---

test/test.js

Connects to https://github.com/bucharest-gold/opossum/issues/68

Fix unhandled promise rejection warnings

---

package.json

chore(package): update jsdoc to version 3.5.2

---

package-lock.json
package.json

fix: build on windows10 due browserify limitations

---

package.json

Fixes: https://github.com/bucharest-gold/opossum/issues/114

build: replace prepublish with prepare

---

Makefile
config/webpack.config.js
package-lock.json
package.json

src: using webpack

---

lib/circuit-helpers.js
lib/circuit.js
lib/symbols.js
test/enable-disable-test.js

Fixes: https://github.com/bucharest-gold/opossum/issues/136

feat: add enable/disable for a circuit

---

config/webpack.config.js
test/browser/index.js

test: ensure all tests are run in the browser

---

README.md

Fix Hapi link

---

lib/circuit.js
test/test.js

feat: pass error as parameter to fallback function

---

examples/jquery/README.md

@lance @lholmquist let me know what you think

Updated README file in JQuery example

---

package-lock.json

The build is currently broken due `lodash`
https://travis-ci.org/nodeshift/opossum/jobs/492860502

chore: fix the build with npm audit fix

---

lib/circuit.js
publish-docs.sh
test/volume-threshold-test.js

Fixes: https://github.com/nodeshift/opossum/issues/276

fix: eliminate bug where circuit can get stuck in halfOpen state forever

---

.circleci/config.yml

Fixes: https://github.com/nodeshift/opossum/issues/290

build: try configuring circleci to ignore gh-pages branch

---

.circleci/config.yml
.gitignore
Makefile
README.md
package-lock.json
package.json

Reenable coveralls and clean up package.json. Eliminates the Makefile.

Build and coverage

---

.circleci/config.yml
README.md
config/webpack.browser.config.js
docs/index.html
docs/opossum.md
lib/circuit.js
lib/prometheus-metrics.js
package-lock.json
package.json
test/circuit-shutdown-test.js
test/health-check-test.js
test/prometheus-test.js

Adds Prometheus metrics to the circuit. As a result,
of limitiations with names in Prometheus, this also
normalizes all circuit event names to camelCase.
Fixes: https://github.com/nodeshift/opossum/issues/247

feat: prometheus client integration

---

index.js
test/prometheus-test.js

Fixes: https://github.com/nodeshift/opossum/issues/327

feat: add function to get metrics for all circuits

---

config/webpack.config.js
package-lock.json
package.json

Choose your own adventure! :)
Alternative implementation of: https://github.com/nodeshift/opossum/pull/379

Implement babel-loader in webpack (without polyfill)

---

lib/circuit.js

Minor tweaks to make my IDE happy while I was working on another PR.

refactor: fix typos and JSDocs in circuit.js

---

.github/workflows/stale.yml

chore: Add stale github action

---

LICENSE

This PR updates the license file to look the same as nodeshift's

Updating license to Apache 2.0

---

lib/circuit.js

doc: fixed the doc issue about allowWarmUp and rollingCountTimeout

---

.github/workflows/api-docs.yml
.github/workflows/release-please.yml

This adds the GH action to create the docs on a release being created.
The other action is the action that creates the releases based on the commits that come in
fixes #461 #462

chore: add gh actions for releasing and doc generation.

---

.github/workflows/nodejs-ci-action.yml
.github/workflows/release-please.yml
CONTRIBUTING.md
docs/assets/anchor.js

Signed-off-by: Michael Dawson <mdawson@devrus.com>

move to main for primary branch

---

package-lock.json
package.json

* now that we are using GH actions and release-please, this module is no longer needed

chore: remove standard-version.

---

.github/workflows/nodejs-ci-action.yml
package.json

chore: add support for node 18

---

.github/workflows/nodejs-ci-action.yml
README.md
package.json

This commit also adds Node 20 to CI
related to #747

feat! remove Node 14

---

.github/workflows/release-please.yml

chore: update release-please action to use node 18

---

test/cache.js

Improve tests for next test cases:
- Using cache with custom get cache key
- Using cache with custom transport

Cache test improvements
