nodeshift/opossum

lib/circuit.js, lib/status.js, test/test.js
The rolling stats window is configurable in both total time sampled, and
how many snapshots, or buckets, within that time frame.
The new options that can be applied to a circuit breaker are
`rollingCountTimeout` and `rollingCountBuckets`, which default to 10000
and 10, respectively. So by default, the window is a statistical view
over the last 10 seconds, consisting of 10 one second snapshots.
The current circuit breaker status api has not been modified directly,
however the expected results are different. For example, you can still
do this:
```js
console.log(`Failure count: ${circuit.status.failures}`);
```
But that count will consist only of the number of failures within the
current snapshot.
To obtain stats for the entire window, use the `window` property.
```js
const stats = …
```
=> feat: circuit status now contains a rolling window

examples/jquery/app.js, examples/jquery/index.html, examples/react/client/package.json, examples/seneca/app.js, examples/seneca/index.html, lib/status.js
The react example has to wait. The way it's built is using webpack and
installing opossum as an npm module.
Fixes: https://github.com/bucharest-gold/opossum/issues/47
=> examples: add stats to jquery and seneca examples

README.md, examples/hystrix/README.md, examples/hystrix/app.js, examples/hystrix/bin/www, examples/hystrix/package.json, lib/circuit.js, lib/hystrix-formatter.js, lib/hystrix-stats.js, test/test.js
DO NOT MERGE - this is a WIP for #39 
I've added a Class, `HystrixStats`, which produces a `stream` of the hystrix metrics.
A circuit breaker will `register` with this class during the creation of a circuit breaker, https://github.com/lholmquist/opossum/blob/status-stream-data/lib/circuit.js#L101 so for every snapshot event emitted, the stats stream is updated.
I'm storing the instance of the circuit that is passed in, in a WeakMap so the hystrix event stream can get a handle on it to give me the circuits name, group, etc..
=> Addition of streaming hystrix data.

index.js, lib/circuit.js, lib/promisify.js, package.json, test/test.js
connects to #51
There was one part were i needed to do a little refactoring to get the tests to pass,  which was how we handled errors in the event of a timeout.   https://github.com/bucharest-gold/opossum/compare/master...lholmquist:51-remove-fidelty?expand=1#diff-dbc2c6ba82726efeb035efaaac7c38acR278 and https://github.com/bucharest-gold/opossum/compare/master...lholmquist:51-remove-fidelty?expand=1#diff-dbc2c6ba82726efeb035efaaac7c38acL356
I also removed the option to specify a different Promise library, not sure if that was part of this though
=> feat: remove fidelity promises.

lib/circuit.js, lib/hystrix-formatter.js, lib/status.js, test/test.js
connects to https://github.com/bucharest-gold/opossum/issues/38
=> WIP - first pass at percentiles

lib/circuit.js, test/test.js
Added an error code `ETIMEDOUT` to easily identify timeout error at caller site. Previously, we need to do checking with e.g. `indexOf('Timed out') >= 0`.
This is useful when we need to abort or cancel the underlying process. The following contrived example tries to depict the usefulness of having `ETIMEDOUT` as `error.code` for when breaker timed out.
```js
const circuitBreaker = require('./');
let handle;
function asyncTimeout () {
return new Promise((resolve) => {
handle = setTimeout(() => {
console.log('timeout!');
resolve();
}, 1000);
});
}
const breaker = circuitBreaker(asyncTimeout, { timeout: 500 });
breaker.fire()
.then(console.log)
.catch((err) => {
// this is very naive but, imagine we have access to abort function for the underlying process
// without this, the asyncTimeout …
```
=> feat: add ETIMEDOUT error code for timeout error

.travis.yml, README.md, lib/circuit.js, lib/hystrix-formatter.js, lib/semaphore.js, lib/status.js, package-lock.json, package.json, test/semaphore-test.js, test/test.js
Also using blue-tape to fix a specific test and
Connects to #60
=> feat: semaphore added

README.md, lib/circuit.js, test/common.js, test/health-check-test.js, test/test.js
Exposes a way for users to provide their own health check function. The provided function
should return a promise. If the promise is rejected, the circuit will open and the `health-check-failed` event will be emitted.
```js
const circuit = opossum(myFunction);
circuit.healthCheck(_ => {
// check the status of the remote service
if (remoteServiceDown) {
return Promise.reject('Cannot connect to remote service');
}
return Promise.resolve();
}, 10000); // check interval - default is 5000
circuit.on('health-check-failed', (err) => {
// send a text message to the poor sysadmin
sendErrorText(err);
});
```
=> Add health check function to a circuit breaker

.travis.yml
This is really only a problem on travis-ci for Node 6 builds.
=> build: conditionally install npm@5 if it's not available

index.js, lib/circuit.js, lib/status.js, test/warmup-test.js
This feature allows the user to let the circuit warm up
before opening, even if every request is a failure or timeout.
The warmup duration is the value provided for
options.rollingCountTimeout.
Fixes: https://github.com/bucharest-gold/opossum/issues/217
=> feat: add options.allowWarmUp as a creation option

lib/hystrix-formatter.js
The hystrix stream data is not compatible with turbine, the specs says that currentTime is a ```Number``` but the provided type is of date string in ```hystrix-formatter.js```. see https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#metrics-publisher
fix #225
=> changed currentTime to number as specified in the docs

index.js, lib/circuit.js, test/volume-threshold-test.js
This option prevents the circuit from opening unless the
number of requests during the statistical window exceeds this
threshold.
Fixes: https://github.com/bucharest-gold/opossum/issues/232
=> feat: add options.volumeThreshold

test/test.js
It seems like setting the function timeout value to 1.1 times
the circuit timeout is too narrow of a time slice. Bumping it to
1.3 times the circuit timeout seems to fix it.
Fixes: https://github.com/nodeshift/opossum/issues/239
=> test: increase timeout value for testing

lib/circuit.js
I create an Error with the existing message and add an error code to match the other type of errors. This also fixes issues with receiving only a string in fallbacks if the breaker is open.
=> fix: error message for open breaker does not have error code.

lib/circuit.js
Regression introduced by https://github.com/nodeshift/opossum/commit/245d47b7bdaed73c6f79fd86df07005690a80486
=> bug: correct max failures check

greenkeeper.json
fixes #275
As discussed in #275 we can remove the examples directory from the greenkeeper.json file so those package.json's are ignored.
=> chore: remove examples from greenkeeper

index.js, lib/circuit.js, test/error-filter-test.js
Refs: https://github.com/nodeshift/opossum/issues/262
~Still requires documentation.~
=> feat: add errorFilter option to bypass incrementing failure stats

lib/circuit.js, test/test.js
This adds the original functions parameters to the timeout and failure events as the third argument.
The third argument will be an array of values
fixes #324
=> Add original function parameters to the failure and timeout events

README.md, lib/circuit.js, lib/prometheus-metrics.js, test/prometheus-test.js
At the moment it is only possible to add prometheus metrics to the global registry of [prom-client](https://github.com/siimon/prom-client).
This adds a `prometheusRegistry` option, that allows to provide a custom, non-global registry.
If a registry is being provided the default metrics will not be added to avoid having duplicate default metrics.
=> feat: add prometheusRegistry option

docs/index.html, docs/opossum.md, index.js, lib/circuit.js, test/browser/index.js, test/circuit-shutdown-test.js
The CircuitBreaker object keeps a Set of instances that have been
created. This change makes a Set Iterator of all circuits that have
not been <code>shutdown()</code>.
Fixes: https://github.com/nodeshift/opossum/issues/340
=> feat: provide an Iterator of all active circuits

package.json
…a release
* Adding the postbump release script allows the docs to be generated after the package.json version bump
* Adding the precommit release script allows those newly generated docs to be part of the release
* the -a flag makes sure to commit generated files
fixes #345
=> chore: docs updated with the correct version number on release

lib/circuit.js, test/circuit-shutdown-test.js
BREAKING CHANGE
This has been shown to cause memory leaks and can effectively
be implemented in user code.
Fixes: https://github.com/nodeshift/opossum/issues/363
=> improvement: stop keeping a set of all circuits

package-lock.json, package.json
It looks like #350 didn't include removing the prom-client dependency
=> chore: remove prom-client as a dependecy

docs/index.html, docs/opossum.md, lib/circuit.js
=> Document options.cache

docs/index.html, docs/opossum.md, lib/circuit.js, test/browser/index.js, test/context-test.js
This allows callers to control the `this` context when firing
a circuit breaker function.
Fixes: https://github.com/nodeshift/opossum/issues/349
=> feat: add call() method to CircuitBreaker

lib/circuit.js
Looks like this is a mistake given `handleError` returns `undefined` and it will always call `resolve` or `reject` that is passed into it first anyway
=> remove unneeded resolve()

lib/circuit.js, test/circuit-shutdown-test.js, test/test.js
Which provides a way of determining if the rejection from `fire()` or `call()` is from the circuit breaker or the action.
E.g
```js
breaker.fire().catch((e) => {
if (CircuitBreaker.isOurError(e)) {
// the system is overloaded
} else {
// unexpected error
}
});
=> implement `isOurError()`

lib/status.js
after shutting down a circuit breaker, these status intervals are persisted and continue to run. This keeps track of each interval and shuts them down.
Edit: attempting to fix the following warning from jest when using `jest --detectOpenHandles`
```
Jest has detected the following 2 open handles potentially keeping Jest from exiting:
●  Timeout
at new Status (node_modules/opossum/lib/status.js:65:20)
at new CircuitBreaker (node_modules/opossum/lib/circuit.js:119:20)
```
=> feat: clear intervals on shutdown

lib/circuit.js, test/closed-test.js
The breaker would close if an earlier task resolved after a later one closed it. This fixes that.
fixes #381
=> Do not close if earlier task resolves when state is not OPEN

lib/circuit.js, test/open-test.js
If `open()` is called I think the reset timer should be reset, as the intent is probably for the circuit breaker to remain open until `close()` is called.
=> Clear reset timer on open()

config/webpack.config.js, index.js, package.json, test/browser/index.js, test/circuit-shutdown-test.js, test/closed-test.js, test/context-test.js, test/enable-disable-test.js, test/error-filter-test.js, test/half-open-test.js, test/health-check-test.js, test/test.js, test/volume-threshold-test.js, test/warmup-test.js
With https://github.com/nodeshift/opossum/pull/380 and https://github.com/nodeshift/opossum/releases/tag/v4.2.0, we are now using Babel to transpile our distribution.
However, I was perplexed... I still get the same error as before, where my app is choking on the use of template literals. I realized the problem is because the distribution folder is not used at all by this library. We ship a transpiled and minified dependency, but don't use either of them by default, because the entrypoint is set to the library path. For the moment I can bypass the error by explicitly using the dist path in my app... `require('opossum/dist/opossum')`.
This pull request updates the package to point to the transpiled distribution of Opossum. Additionally, it only ships the `dist` folder, not the `lib`, so …
=> Set entrypoint to dist/opossum.js

lib/circuit.js, test/common.js, test/error-filter-test.js, test/half-open-test.js
=> Fix stuck halfOpen when using errorFilter

lib/circuit.js, test/test.js
Allow `false` to be provided for the `timeout` option as a means of disabling the entire feature.
Note that the logic to skip the timeout feature if the option is falsey was still in place was did not need an update for this fix.
https://github.com/nodeshift/opossum/blob/30a83b361fc0e61f111ff846709712e9c476c77d/lib/circuit.js#L495
I'm not sure a good way to test this beyond monkey-patching the global `setTimeout` and asserting it wasn't called. So I haven't added a test, but would be happy to add one if there is a preferred method. 
Fixes #393.
=> fix(circuit): allow timeout option to be false

.circleci/config.yml
we've already updated the engine param in the package.json,  but we need to also remove the node8 tests from the circleci config
this will just be a patch release since we've already did the "remove node 8" stuff
=> chore: remove node8 from circle ci config

test/test.js
This commit avoids an UnhandledPromiseRejectionWarning to be throwing
from `'Breaker resets after a configurable amount of time when multiple
jobs fail'` test.
=> fix(test): Avoiding an UnhandledPromiseRejection

README.md
Related to #459 
@lance @lholmquist I'm not 100% sure if we need to run `npm run build:docs` before to send the PR when updating the docs.
=> Adding docs about fallback parameters

.github/workflows/nodejs-ci-action.yml
Coverage uploads require access to a repository secret, which isn't
accessible to pull requests from forks with the `pull_request` event.
Refs: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks
=> build: use pull_request_target in actions workflow

README.md
GreenKeeper was sunset in June 2020. Dependency updates are covered
by a combination of David and Snyk.
=> docs: remove GreenKeeper badge

README.md
Too me a few to realize they are same thing.
Most APIs in the readme are using `breaker`. And all test files are using `breaker`.
So here change the rest `circuit` to `breaker` for consistency.
=> docs(readme): use breaker for consistency

README.md
Took me a while continuing reading to realize `params` is actually `x, y` in the above function.
```js
function asyncFunctionThatCouldFail(x, y) {
return new Promise((resolve, reject) => {
// Do something, maybe on the network or a disk
});
}
breaker.fire(params) // here change to x, y to match above function
.then(console.log)
.catch(console.error);
```
=> docs(readme): change params to x, y to match

README.md
`maxFailures` is deprecated. The new recommended way is using `errorThresholdPercentage`.
=> docs(readme): update maxFailures to errorThresholdPercentage

lib/circuit.js
=> doc: fix docs related to allowWarmUp and rollingCountBuckets

lib/circuit.js, test/error-filter-test.js
When the circuit invocation fails, and there is an error filter in place,
this change provides the function invocation parameters as the second
parameter to `errorFilter()`.
Fixes: https://github.com/nodeshift/opossum/issues/489
Signed-off-by: Lance Ball <lball@redhat.com>
=> feat: pass circuit params to error filter

lib/circuit.js, test/test.js
When a fallback function is called and throws an exception, the circuit
breaker should catch the exception and return a rejected Promise.
See: https://github.com/nodeshift/opossum/issues/509
Signed-off-by: Lance Ball <lball@redhat.com>
=> fix: catch exceptions in fallback functions

lib/circuit.js
This is a quick fix to avoid the following error when no action is passed in the constructor:
TypeError: Cannot read property 'name' of undefined
Related to #514
=> fix: using default parameter to avoid runtime error

.eslintrc, lib/circuit.js, package-lock.json, test/test.js
Throwing a TypeError if the action parameter is not provided. #524
=> TypeError on empty action

package-lock.json, package.json
* Webpack 5 breaks the build since it has changed how it brings in the node core polyfills
=> chore: downgrade webpack to 4.x

lib/circuit.js, test/error-filter-test.js, test/half-open-test.js
This address #540 and is a semver change
=> Successful error filter shouldn't invoke the fallback function

lib/circuit.js
This PR is a very small documentation fix. The `rollingPercentilesEnabled` option is documented as defaulting to false, but rolling percentiles are [enabled by default](https://github.com/nodeshift/opossum/blob/16341bb806c14fec29cb25e7bd301e975ae23631/lib/circuit.js#L123) (and the corresponding [test](https://github.com/nodeshift/opossum/blob/16341bb806c14fec29cb25e7bd301e975ae23631/test/test.js#L811)) unless `rollingPercentilesEnabled` is explicitly set to `false`.
=> docs: Fix documentation for default value of rollingPercentilesEnabled

lib/circuit.js, test/error-filter-test.js, test/half-open-test.js
This commit reverts some of the behavior changes in
https://github.com/nodeshift/opossum/pull/556. In that PR, the intent
was to avoid calling the fallback function when an an invocation error
is filtered by a user supplied `errorFilter` function. It did
accomplish that, however, it also changed how a function resolves
in the case of a filtered error. Previously, even though the error
was filtered, the function invocation would return the error to the
caller. With #556, this changed so that the caller instead receives
simply a truthy value.
This commit reverts that behavior so that the error is returned.
While it may seem counter intuitive to return an error when the it
was filtered by a user supplied `errorFilter` function, there are good
reasons to do so. It provides the caller with …
=> fix: return error from invocation when error filter filtered errors

.github/workflows/nodejs-ci-action.yml, package.json
Node.js 16 released. I think we can use 16 now.
For 15, since it is a short life version, so I think we can remove it.
(If you have concern to let Node.js 15 apps have a smooth migrating, just let me know. I can leave 15 there)
Thanks!
=> chore(node): support Node.js 16

.eslintrc, README.md, lib/circuit.js, lib/status.js, test/status-test.js, test/test.js
For this first pass, i've only added the ability to import a previous stats object in.  
I'm not sure if we need to import the state of a breaker(closed, open, half-open, etc...) but that is something we can iterate on.
relates to #504
=> feat: Add the ability to prime a breaker with previous stats

README.md, lib/circuit.js, package.json, test/state-test.js, test/status-test.js
This PR is a continuation of #568.  That last PR only allowed a user to prime the circuit breaker with the stats of the circuit.  This part adds the ability to prime the breaker with a starting state.  To make it easier for users to see there state, and ultimately save it some where, the `exportState` function has been added.
To create a Circuit with states, there is now a `state` parameter in the options.  Creating a new circuit might look like this:
```
const state = {
....
}
const breaker = new CircuitBreaker({state: state});
// to export the state
const breakerState = breaker.exportState();
```
I updated the README with some samples of how this would work
The only part i'm not thrilled with is but is probably ok, is that during initilization, if you prime a circuit to be open, then …
=> feat: initialize the state of a breaker on creation

README.md, lib/circuit.js, test/circuit-shutdown-test.js
fixes #620
currently, when shutdown is called, it removes all the listeners before it emits the shutdown event, this moves the call to emit the shutdown event before the listeners are removed
=> fix: breaker should emit a shutdown event when it is shutdown

README.md
Change example of error threshold percentage section in according to the described fired times.
=> docs: change example of error threshold section

README.md, lib/circuit.js
remove the options.maxFailures condition check when deciding if the circuit should be opened
It's a bit misleading when looking at the source code, where we are still comparing the `options.maxFailures` value when deciding if the circuit should be opened. Same issue on the documentation. We should remove the deprecated option from the checking logic to avoid confusion
=> chore: remove the options.maxFailures condition check

README.md, lib/circuit.js, test/test.js
Addresses https://github.com/nodeshift/opossum/issues/673
This PR adds `AbortController` support in Opossum. This is useful in
conjunction with the timeout feature, where Opossum will signal upon
timeout and allow users to cleanly abort their ongoing requests.
See links:
- https://developer.mozilla.org/en-US/docs/Web/API/AbortController
- https://nodejs.org/api/globals.html#class-abortcontroller
- https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#aborting_a_fetch
- https://nodejs.org/api/http.html#httprequesturl-options-callback
=> feat: adds `AbortController` support

.github/workflows/nodejs-ci-action.yml, package.json, test/browser/index.js
Because some of the dependabot / snyk PRs could update dependencies like webpack and friends, these checks should be included for pull requests.
Signed-off-by: Lance Ball <lball@redhat.com>
=> chore: update CI to include build+test:headless

lib/circuit.js, test/state-test.js
When a circuit is reinitialized with state from a previous instance, if the previous circuit was closed but the reset timeout has passed since reinitialization, the circuit should enter halfOpen immediately.
Fixes: https://github.com/nodeshift/opossum/issues/719
Signed-off-by: Lance Ball <lball@redhat.com>
=> feat: enter halfOpen state on reinitialization if required

lib/circuit.js, lib/status.js, test/status-test.js
Hello! I had a small feature request
Motivation
As I understand it, every bucket_interval (1s by default), opossum emits a snapshot of the stats in the Status class
this[SNAPSHOT_INTERVAL] = setInterval(_ => this.emit('snapshot', this.stats), bucketInterval);
My app doesn't actually listen to these stats and the extra call to setInterval clogs up the memory
Solution
Could we have a configurable option to disable the stats snapshots, thereby removing the extra call to setInterval?
Issue here: https://github.com/nodeshift/opossum/issues/798
=> feat: add option to disable stats snapshots

lib/circuit.js, test/options-test.js, test/test.js
when setting things like resetTimeout and errorThresholdPercentage to 0, the default value was being used since zero is a false-y value.  Adding the [nullish coalesce operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#assigning_a_default_value_to_a_variable) fixes it 
fixes #824
=> fix: fix bug where options couldn't be set to zero.

lib/status.js
#827 should stop with this change.
=> Fix for Max Stack Depth issue

.github/workflows/nodejs-ci-action.yml, package.json
Node.js 22 is released and testing opossum with it works fine for me in automated tests and real project usage. 
Therefore this PR to add v22 as supported engine.
=> chore: add support for nodejs 22

README.md, lib/cache.js, lib/circuit.js, lib/status.js, package-lock.json, test/browser/index.js, test/cache.js
To not break existing functionality, I chose to not modify the cache behavior but introduce a second one.
If options.coalesce is set, multiple calls to the circuitbreaker will be handled as one, within the given timeframe (options.coalesceTTL).
If true, this provides coalescing of requests to this breaker, in other words: the promise will be cached.
Only one action (with same cache key) is executed at a time, and the other pending actions wait for the result. Performance will improve when rapidly firing the circuitbreaker with the same request, especially on a slower action (e.g. multiple end-users fetching same data from remote). Will use internal cache only. Can be used in combination with options.cache.
Additional fix/feature:
feature: max cache size
To prevent internal cache from …
=> feature: coalescing calls + feature: max cache size

lib/circuit.js, test/enable-disable-test.js
To revert to previous behaviour up to v8.1.4.
https://github.com/nodeshift/opossum/issues/894
=> fix: disabled breaker emits fire events

README.md, lib/circuit.js, test/test.js
Introducing a new option to the CircuitBreaker: `autoRenewAbortController`. When enabled, this flag automatically recreates the AbortController whenever the CircuitBreaker state transitions to 'halfOpen' or 'closed'. This ensures the controller is reset and ready for reuse in subsequent state changes.
Closes #861
=> feat: renewing the AbortController when the circuit enters the 'halfClose' or 'close' state

lib/circuit.js, test/cache.js
Bugfix: coalesce re-used empty cachekey when cache was not used.
Bugfix: emit fire when circuitbreaker is disabled.
=> Bugfix for 8.20.0

lib/cache.js, test/cache.js
See https://github.com/nodeshift/opossum/issues/904
=> Fixed: Incorrect default value of maxEntries for MemoryCache #904

README.md, lib/cache.js, lib/circuit.js, test/cache.js
After implementing coalescing in our software, we noticed it would be handy to better finetune coalescion behavior. 
So added the option to reset coalescion cache at different stages: error, success, timeout. This can be used as sometimes you'd like to retry after an error/timeout, or would like to limit cache TTL without limiting coalescion TTL (e.g. a slow action to fetch data you do want to execute as often as possible but never twice at the same time).
=> feature: Coalesce reset options, reset coalesce based on result. (error, success, timeout)
